version: '3'
services:
  my_sql_db:
    image: percona:latest
    container_name: my_sql_db
    environment:
      MYSQL_ROOT_PASSWORD: Betawi45!
      MYSQL_DATABASE: aidentity
    ports:
    - 13306:3306

  migration:
    image: boxfuse/flyway:latest
    container_name: flyway_migration
    volumes:
      - ./src:/flyway/sql
    command: -url=jdbc:mysql://my_sql_db:13306 -schemas=aidentity -user=root -password=Betawi45! -connectRetries=30 migrate
    depends_on:
    - my_sql_db
