version: '3'
services:

  migration:
    image: boxfuse/flyway:latest
    container_name: flyway_migration_3
    volumes:
      - ./flyway_scripts/src:/flyway/sql
    command: -url=jdbc:mysql://localhost:3306 -schemas=mate -user=root  -connectRetries=10 migrate
