version: '3'
services:

  migration:
    image: boxfuse/flyway:latest
    container_name: flyway_migration_3
    volumes:
      - ./flyway_scripts/src:/flyway/sql
    command: -url=jdbc:mysql://127.0.0.1:3306 -schemas=aidentity3 -user=root -password=Betawi45! -connectRetries=30 migrate
