version: 2.1

orbs:
  python: circleci/python@0.2.1
  

jobs:
  build-and-test:
    parameters:
      stage:
        type: string

    executor: python/default
    steps:

      - run: echo  '--template template.yaml --parameters-override AppStage=<<parameters.stage>> '
      - run: echo ' '${CIRCLE_BRANCH}'_USERPATH'
      - checkout
      - run: 
          command: |
            dir .
            pwd
      # - run:
      #     command: |
      #       set -x
      #       docker-compose up -d


      # - checkout
      # - python/load-cache
      # - python/install-deps
      # - python/save-cache
      # - run:
      #     command: ./manage.py test
      #     name: Test

workflows:
  main:
    jobs:
      - build-and-test:
          stage: blue
